### ISSUE TITLE
Filtering?

### ISSUE THREAD

**Issue by foucdeg** [nolanlawson/pouchdb-dump-cli#11]
This is a question rather than an issue: is it possible to filter the dump, just as one would filter a replication?

**Comment by foucdeg** [comment]
I guess this comes down to #2 .

**Comment by nolanlawson** [comment]
Actually on second thought, I think it might make more sense to say that this should be a plugin on top of pouchdb-replication-stream. Since it's just a stream, there's no reason that a consumer couldn't do whatever filtering they wanted.

In practical terms, using pouchdb-dump-cli, you could also simply go through each line of the file and remove documents that don't fit whatever criteria you have. Another option is to replicate from one database to a filtered database (using filtered replication; you can set up CouchDB to do this regularly using the `_replicator` database), then dump from the filtered database.
